spring:
  application:
    name: gestion-client-api
  datasource:
    url: jdbc:mysql://localhost:3306/gestionclient?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    #password: root
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: MYSQL
    show-sql: true

# pictures
app:
  pictures:
    directory: /home/zzadmin/IdeaProjects/stef/pictures
