server:
  port: 8082

spring:
  application:
    name: gc-graphql

eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/


app:
  services:
    clients:
      #      url: http://localhost:8080
      name: gestion-client-api