spring:
  datasource:
    url: jdbc:mysql://ENV_MYSQL_SERVER:3306/gestionclient?useUnicode=true&characterEncoding=utf8&useSSL=false

app:
  pictures:
    directory: /ENV_PICTURES_FOLDER

eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://ENV_EUREKA_SERVER:8761/eureka/
