spring:
  application:
    name: gestion-client-api
  datasource:
    url: jdbc:mysql://localhost:3306/gestionclient?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    #password: root
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: MYSQL
    show-sql: true

# pictures
app:
  pictures:
    directory: /home/zzadmin/IdeaProjects/stef/pictures

# Eureka registry
eureka:
  instance:
    # for docker: use IP address, not DNS name  (proxy settings: bypass 10.0.0.0/8)
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://ENV_EUREKA_SERVER:8761/eureka/
